### ISSUE TITLE
Empty Detections for Auto Annotation

### ISSUE THREAD

**Issue by Georg-W** [peyman-sabouri/alexyAB_to_openvino#1]
Hi I am trying to parse a custom trained yolov3 model into CVAT for auto-annotating videos. 
Have you tried uploading your scripts together with a model into the dashboard and ran annotations?
CVAT lets me upload the model & trigger the annotation, but there are no annotations getting created.
Could you tell me what adaptions you make when using your project as an auto-annotation upload?

Thx

**Comment by peyman-sabouri** [comment]
@Georg-W Hi, you can use "docker cvat log" to see the output of the inference (detections) if you print the detection. I have described the process in the README.  I used inference_yolov3.py as the python file for CVAT.

**Comment by Georg-W** [comment]
@peyman-sabouri thank you for the advice, working now!
